### ISSUE TITLE
Some files assume SVN placeholders exist

### ISSUE THREAD

**Issue by eric-wieser** [cmorty/lejos#1]
For example, https://github.com/cmorty/lejos/blob/master/startup/src/lejos/nxt/startup/GraphicStartup.java#L75

**Comment by cmorty** [comment]
Well, there's nothing I can really do about it. There are some scripts that fix things, but you need to run them locally. Otherwise, if someone else creates a git-repo using svn-git without those scripts, the hashes will differ making those repos incompatible. The best thing of course would be if the official repo would move to git.

**Comment by eric-wieser** [comment]
I've put this as an issue not to ask you to fix it, but to point out to users of the repo that this is something to watch out for.
